name: "hello workflow" #name  of workflow pipwline

on:
    push:
      branches:
        - main
        - production
jobs:
   hello_world:   # name of the job
    runs-on: ubuntu-latest  

    steps:
        - name: "print hello world"
          run: echo "hello world:"
        - name : "print cuurent date"
          run: date